name: Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: auto generator by dockerhub
        run: |
          bash download.sh
          export SYNC_DIR=docs/docker
          export SYNC_HUB=docker.io/labring
          /tmp/cluster-image-docs
      - name: auto generator by aliyun
        run: |
          rm -rf docs/aliyun-shanghai
      - uses: peter-evans/create-pull-request@v7
        with:
          title: 'workflow: Automated Workflow Update for ${{steps.get-current-tag.outputs.tag }}'
          body: |
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          commit-message: |
            🤖 add workflow change for images.
          branch: workflow
          base: main
          signoff: true
          delete-branch: true
          reviewers: cuisongliu
          branch-suffix: short-commit-hash
          labels: sync-docs
