name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.20.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release  --timeout=1h
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          USERNAME: ${{ github.repository_owner }}
